spring.application.name=gateway
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=gateway;encrypt=true;trustServerCertificate=true;
spring.datasource.username=root
spring.datasource.password=root1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
HMAC_SECRET_KEY="YOUR_HMAC_SECRET_KEY"